import os

env = Environment( ENV = { 
    'PATH' : os.environ['PATH'], # These environment variables are required by colorgcc.
    'TERM' : os.environ['TERM'],
    'HOME' : os.environ['HOME']
} )

SetOption( 'num_jobs', 2 ) # Set this to the number of processors you have.  TODO: Automate this.

target = 'afe'
common_dir = '../common/'
libraries = [ 'SDL', 'SDL_image', 'GL', 'GLU', 'GLEW', 'm', 'CEGUIBase', 'CEGUIOpenGLRenderer' ]
compiler_warnings = '-Wall -W -Wshadow -Wpointer-arith -Wcast-qual -Wwrite-strings -Wconversion -Winline -Wredundant-decls -Wno-unused'
compiler_flags = '-g ' + compiler_warnings + ' -DNO_SDL_GLEXT'
include_paths = [ common_dir, '/usr/include/CEGUI' ]
common_sources = [ 'geometry.cc', 'utilities.cc', 'cegui_utilities.cc', 'sdl_gl_interface.cc', 'drawing_utilities.cc' ]
sources = [ Glob( '*.cc' ), Glob( 'generators/*.cc' ), [ common_dir + source for source in common_sources ] ]

env.Command( 'tags', sources + Glob( common_dir + '*.h' ) + Glob( '*.h' ) + Glob( 'generators/*.h' ), 'ctags -o $TARGET $SOURCES' )

env.Program( source = sources, target = target, LIBS = libraries, CCFLAGS = compiler_flags, CPPPATH = include_paths )
